Ecp 9342
Adyen/adyen-integration-tools-tests pull request #120
Opened 2024-08-07 14:16 UTC by SushmitaThakur

## Summary

## Tested scenarios

**Fixed issue**:

2024-08-07 14:55 UTC, raoulritter requested changes

2024-08-07 14:55 UTC, raoulritter commented on projects/magento/pageObjects/plugin/MultishippingSuccess.page.js
> +        // await page.pause();
Remove

2024-08-07 14:55 UTC, raoulritter commented on projects/magento/tests/BancontactCardPayment.spec.js
> +
Remove

2024-08-07 15:04 UTC, raoulritter submitted a review, later dismissed

2024-08-08 09:36 UTC, peterojo approved these changes

2024-08-08 09:37 UTC, merged